### ISSUE TITLE
Generating queue URL's with wrong path

### ISSUE THREAD

**Issue by puppeteer701** [softwaremill/elasticmq#462] opened 2021-03-05 13:02 UTC
With the latest docker image https://hub.docker.com/layers/softwaremill/elasticmq/latest/images/sha256-6e197da81fe3df68cd386a2e02b6e707578671877b77addacaf15baa0e939eea?context=explore I have noticed that URL's generated for the queue are potentially wrong.

```
 ResponseMetadata: { RequestId: '00000000-0000-0000-0000-000000000000' },
  QueueUrls: [
    'http://localhost:9324/000000000000/test',
    'http://localhost:9324/000000000000/default.fifo'
  ]
```

## Conf
```
queues {
  default {
    defaultVisibilityTimeout = 10 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }

  test {
    defaultVisibilityTimeout = 10 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }
}
```

## Code
```
const sqs = new SQS({
    region: awsRegion,
    accessKeyId: awsKey,
    endpoint: 'http://localhost:9324',
    secretAccessKey: awsSecret,
  });

  void (async () => {
    const queues = await sqs.listQueues().promise();
    console.log(queues);
  })();
```

In version 1.0 it works as expected.

**Comment by rojekp** [comment] 2021-04-13 08:49
Ok, you're right - URL's generated for the queue have changed. But it was made intentionally according to this issue: https://github.com/softwaremill/elasticmq/issues/421

**Comment by adamw** [comment] 2021-09-10 11:49
Closing, as far as I understand this is not a bug, but works as expected

**Closed by adamw** 2021-09-10 11:49 UTC
