### ISSUE TITLE
--message-attributes not added to the actual message headers

### ISSUE THREAD

**Issue by amit115532** [softwaremill/elasticmq#159] opened 2018-12-08 19:39 UTC
The following url should create a message with a string attribute: `type: create-business` 

`aws sqs send-message --endpoint-url http://localhost:9324 --queue-url http://localhost:9324/queue/business-background.fifo --message-body '{"msg": "test"}' --message-group-id "test" --message-attributes '{"type" : {"DataType":"String","StringValue":"create-business"}}'`

The message is created but without the attribute inside headers
when using the same command with the real sqs endpoint-url it works.

**Comment by onnimonni** [comment] 2018-12-19 14:54
I was wondering this same thing today. This is first time I'm using elasticmq so I have no idea if this is intended behaviour or not 🤷‍♂️

**Comment by Opalo** [comment] 2019-02-20 15:28
@amit115532 what do you mean that the message is created but without attributes? I assume that when you receive the message the attributes are not present in the body? Is my understanding correct?

**Comment by Opalo** [comment] 2019-02-21 11:23
I've tested it thoroughly on both local and remote (AWS SQS) environments and found no evidence that this issue do exist. Here, are the logs from the tests I did:
- [local](https://gist.github.com/Opalo/b6d5c69977b5fc05e882907ef3881c39)
- [remote](https://gist.github.com/Opalo/759cb6bf5fdcdf02020cb07915d7957a) 

When you look into the [documentation](https://docs.aws.amazon.com/cli/latest/reference/sqs/receive-message.html) related to receiving a message from the queue you can notice that there are two types of attributes:
- message attributes (related to the message itself)
- attributes (it would be better to call it meta attributes)

To get both of them you need to use the switches, respectively:
- `--message-attributes <VALUE>` 
- `--attributes <VALUE>` 

When `All` is used (for both switches) you'll get all the attributes. When none of the switch is present the default `receive-message` format is returned. 
The code responsible for returning the attributes can be found in [this](https://github.com/softwaremill/elasticmq/blob/develop/rest/rest-sqs/src/main/scala/org/elasticmq/rest/sqs/ReceiveMessageDirectives.scala) class.

**Comment by heroldus** [comment] 2019-03-05 10:01
@Opalo You are right, setting *All* does the trick, but SQS support also some simple wildcard logic to select the message attributes to receive. See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html You can set `--message-attributes '*'` which is equivalent to *All* which is currently not supported in ElasticMQ. Maybe this is a missing feature, but nevertheless it's a really helpful project, thanks!

**Comment by Opalo** [comment] 2019-03-05 21:31
@heroldus it's not `*` but `.*` (as you can read [here](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html)) and it's [supported](https://github.com/softwaremill/elasticmq/blob/develop/rest/rest-sqs/src/main/scala/org/elasticmq/rest/sqs/ReceiveMessageDirectives.scala#L101) in elasticmq. I'm closing this "issue".

**Closed by Opalo** 2019-03-05 21:31 UTC

**Comment by heroldus** [comment] 2019-03-05 22:45
@Opalo `*` works as well for message attributes on SQS even if it's not documented. That's why I ran into the different behaviour of SQS and ElasticMQ. But don't take this as a feature request.

**Comment by Opalo** [comment] 2019-03-11 06:57
@heroldus you're welcome to prepare a PR which will make both `.*` and `*` work :)
