### ISSUE TITLE
Successfully sent messages are not received sometimes

### ISSUE THREAD

**Issue by sedovalx** [softwaremill/elasticmq#469] opened 2021-04-04 12:59 UTC
In our project, we use `elasticmq` in tests because its api compatibility with SQS. I noticed that these tests are flaky, and sometimes we don't receive some expected events from the elasticmq queue. I managed to exctract the related logic into a "minimalistic" project and rewrote it from a different JVM language to Scala for the convenience. Here is the project sources https://github.com/sedovalx/elasticmq-message-loss. I really hope that it's just me doing something in a wrong way. 

The code inside creates 2 queues - the main one and the DLQ. The target is either an embedded elasticmq instance or AWS SQS. Then, it generates and sends messages of 2 types to the main queue in batches. There is a background thread that polls the queue, splits the events by type and either deletes events in batches or changes their visibility timeout (sets 1 hour). Then, after all generated events are sent, the code starts to wait until all sent events are received by the polling thread and processed - either deleted or changed.

With enough iterations of the scenario above, the execution fails with an assertion because some expected messages are missing in the queue. I've tried to enable the debug logging for the `org.elasticmq` logger ans saw that in case of failure the number of `org.elasticmq.actor.queue.QueueActor [] - my-queue: Sent message with id ...` and `org.elasticmq.actor.queue.QueueActor [] - my-queue: Receiving message` log messages in the same test iteration don't match. Iterations don't intersect in sent/received messages.

I've run the same test with default settings on SQS and it passed. It made me think that the behavior of elasticmq is a bit different. 

PS: in the mentioned project, the execution doesn't stop by itself at the end of the program. I noticed some akka threads are still running.

**Comment by Pask423** [comment] 2022-04-25 09:05
Closing due to reproduction issues. 
To reopen please provide simpler example for reproducing issue.

**Closed by Pask423** 2022-04-25 09:05 UTC
