### ISSUE TITLE
Fifo delay queue is delivering messages immediately instead of delaying them

### ISSUE THREAD

**Issue by jcelmeta14** [softwaremill/elasticmq#890] opened 2023-10-26 15:33 UTC
Hello!

I have a queue configured in the `.conf` file as follows:

```
  MyQueue {
    fifo = true
    delay = 60 seconds
    defaultVisibilityTimeout = 60 seconds
    deadLettersQueue {
      name = "MyDLQueue"
      maxReceiveCount = 3
    }
  }
```

As you may see, the queue has a delay of 60 seconds. The queue seems to have been created correctly. I checked using the CLI:

<img width="606" alt="image" src="https://github.com/softwaremill/elasticmq/assets/22294784/11762444-6d65-4fa3-b77f-5031d9b2b791">

The problem is that regardless of the configuration, the messages get delivered immediately. I am using `serverless-framework` and I have configured a function to have the queue as an event source. As soon as a message is sent to the queue, the function get triggered immediately without the delay of 60 seconds.

Am I doing something wrong?

Thank you!

**Comment by micossow** [comment] 2023-11-02 08:44
@jcelmeta14 I can't reproduce the issue.
I'm using `softwaremill/elasticmq-native:1.4.7` and the following configuration:
```
include classpath("application.conf")

queues {
  main {
    defaultVisibilityTimeout = 10 seconds
    delay = 2 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "retry"
      maxReceiveCount = 1
    }
  }
  retry {
    defaultVisibilityTimeout = 10 seconds
    delay = 2 seconds
    receiveMessageWait = 0 seconds
  }
  delayed {
    fifo = true
    delay = 10 seconds
    defaultVisibilityTimeout = 10 seconds
    deadLettersQueue {
      name = "retry"
      maxReceiveCount = 3
    }
  }
}
```

and this is my test code:
```python
queue = self.sqs.get_queue_by_name(QueueName='delayed.fifo')
queue.send_message(MessageBody='some test message to be delayed', MessageGroupId='group123', MessageDeduplicationId='dedup123')
messages = queue.receive_messages()
print(messages)
time.sleep(5)
messages = queue.receive_messages()
print(messages)
time.sleep(5)
messages = queue.receive_messages()
print(messages)
```

and this is the output:
```
[]
[]
[sqs.Message(queue_url='http://localhost:9324/000000000000/delayed.fifo', receipt_handle='b5edfb66-0106-43b7-beb4-e7ab211a82f0#c732fdcd-aa1c-4d78-af5c-00a7b2878ce1')]
```

If you still observe the issue with the latest version, please provide an application or test reproducing it.

**Comment by jcelmeta14** [comment] 2023-11-06 16:02
Thank your for your reply! I will try to create a repo in the following days, and I will post another comment here.

**Comment by tmnsur** [comment] 2024-06-05 22:24
The issue happens when the "DelaySeconds" is set to 0 within the message. If you modify your test code like this:

`queue.send_message(MessageBody='some test message to be delayed', MessageGroupId='group123', MessageDeduplicationId='dedup123',DelaySeconds=0)`

You would observe in `src/main/scala/org/elasticmq/rest/sqs/SendMessageDirectives.scala` line 131:

```
val delaySecondsOption = parameters.DelaySeconds match {
      case Some(v) if v < 0 || v > 900 =>
        // Messages can at most be delayed for 15 minutes
        throw SQSException.invalidParameter("DelaySeconds must be >= 0 and <= 900")
      case Some(v) if v > 0 && queueData.isFifo =>
        // FIFO queues don't support delays
        throw SQSException.invalidQueueTypeParameter(DelaySecondsParameter)
      case d => d
}
```

that `delaySecondsOption` is set as 0, and this causes `nextDelivery` in line 142 to be assigned to AfterMillisNextDelivery(0), and that will cause the sender to send the message immediately instead of waiting for the queue-wide `DelaySeconds` configuration.

I prepared this PR to fix this: https://github.com/softwaremill/elasticmq/pull/1009

**Closed** 2024-06-13 08:37 UTC
Labels: awaiting-user-input
